# Generated by Django 2.2.27 on 2022-05-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220508_0125'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='uniq_tags'),
        ),
    ]
