# Generated by Django 2.2.27 on 2022-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220505_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Ланч'), ('dinner', 'Обед'), ('supper', 'Ужин')], max_length=200, verbose_name='Название тега'),
        ),
    ]
