# Generated by Django 2.2.27 on 2022-05-10 23:23

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220508_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
