# Generated by Django 2.2.27 on 2022-05-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorited',
            name='author',
        ),
        migrations.AddField(
            model_name='favorited',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
